title       = "mealdb"
baseURL     = "https://mealdb-cli.tamnd.com/"
description = "A command line for mealdb."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mealdb-cli"
